### ISSUE TITLE
Cannot install demo

### ISSUE THREAD

**Issue by KissBalazs** [fbessou/angular2-schema-form-demo#8]
Hi there,

The Demo for me does not start. I did

1. git clone repository
2. npm install
3. npm start

that results in this error (after successfully downloading dependencies) :
```
ERROR in ./src/main.browser.ts 
Module build failed: TypeError: Cannot read property 'exclude' of undefined at applyDefaults (/home/forestg/projects/temp/angular2-schema-form-demo/node_modules/awesome-typescript loader/src/instance.ts:266:72)
at Object.ensureInstance (/home/forestg/projects/temp/angular2-schema-form demo/node_modules/awesome-typescript-loader/src/instance.ts:145:5) 
at compiler (/home/forestg/projects/temp/angular2-schema-form-demo/node_modules/awesome-typescript loader/src/index.ts:37:20)
at Object.loader (/home/forestg/projects/temp/angular2-schema-form-demo/node_modules/awesome-typescript-loader/src/index.ts:18:18)
```

my npm version is 4.1.1, NodeJS is 7.4.0 and Angular 2.4.3. Am I doing something wrong?

**Comment by fbessou** [comment]
The demo must be outdated, I'll take a look at it during the WE.

**Comment by Nayana-Manchi** [comment]
Same error as above. By when can we expect the fix?

**Comment by fbessou** [comment]
The demo should be working now !

**Comment by avalonabecker** [comment]
I get "Cannot find module 'rxjs/symbol/observable'" Error: Cannot find module 'rxjs/symbol/observable'
    at Function.Module._resolveFilename (module.js:469:15)
Using node 6.9.5, npm 3.10.10

**Comment by AlecTaylor** [comment]
```
[default] Checking started in a separate process...
[default] /tmp/angular2-schema-form-demo/node_modules/@types/jasmine/index.d.ts:39:38 
    A parameter initializer is only allowed in a function or constructor implementation.
[default] /tmp/angular2-schema-form-demo/node_modules/@types/jasmine/index.d.ts:39:46 
    Cannot find name 'keyof'.
[default] /tmp/angular2-schema-form-demo/node_modules/@types/jasmine/index.d.ts:39:52 
    '=' expected.
[default] Checking finished with 3 errors
```

tsc Version 2.1.5, npm 4.1.2, node 7.7.1

**Comment by aitorjs** [comment]
[Pull request ](https://github.com/fbessou/angular2-schema-form-demo/pull/9/commits) upgrading dependencies of angular2-schema-form and angular-cli, among of things.

[Here](https://github.com/aitoribanez/angular2-schema-form-demo) is the demo using this pull request.

Hope it helps!

**Comment by intelinc** [comment]
Thanks @aitoribanez! Your updated version fixed the issues I was having running the demo.
